### ISSUE TITLE
Streaming a Video and a String in Real time

### ISSUE THREAD

**Issue by addi1992** [miguelgrinberg/flask-video-streaming#19]
Hi,
I am building a real time face recognizer wherein I am streaming an openCV webcam frame (image with rectangle around face and name of an individual printed on jpeg) to a web client. I would like to yield a string along with the existing jpeg in the gen() function and capture it in index.html. I understand I could yield the string alongside the jpeg, but not sure how to handle it in front end. I want to stream the video as well as print the name of the person on the front end.  Could you please help with this?

Thanks,
AK

**Comment by miguelgrinberg** [comment]
if the stream that you transfer is not in Motion JPEG, then you have to implement your own video player for the client, the standard one can only play the stream when it is just a sequence of jpeg images.

**Comment by Tomeu7** [comment]
Hello miguel,

I am trying to build something similar to addi, could you elaborate more on that? I can return a string + frame on the camera class (using get frame) but then I have no idea how to process it with the Response flask function. The idea is to write the string in the web page.

Any help would be appreciated, thanks.

**Comment by miguelgrinberg** [comment]
Adding the string would make the stream incompatible with the motion jpeg standard, so the browser will not play it.

You can implement your own stream format by returning the jpeg plus the string in any way you like. For example, your frame payload can be the string, a separator (a comma or similar) and then the jpeg data. Then you will need to read the stream using an asynchronous request from JavaScript, extract the string and the jpeg, and then draw the jpeg frames and display the strings yourself using JavaScript APIs available in the browser.

**Comment by potoo0** [comment]
I have similar situation as the above all. I have some data extract from frame, and want display both of this data and frame on web, but it will be blocked when using stream, so I guess maybe I can use flash to send data, use return Response for motion JPEG. I tried send two parts of data, my script like this : `yield frameStream, data`. `frameStream, data = next(gen(para)); flash(var); return Response(frameStream, ...)`. but it didn't work.

**Comment by miguelgrinberg** [comment]
@potoo0 I don't think that approach is going to work. As I said above, you need to implement your own custom streaming format on both sides. Instead of using the streaming feature in Flask, you may also want to consider using a WebSocket connection.

**Comment by potoo0** [comment]
@miguelgrinberg Thanks for your patience and time. Sorry for replying late. I am seeing your feedback in real time, but I will not be able to reply soon... Your approach has kind of difficult, but I am working on it.

**Comment by buaacarzp** [comment]
Hey, it's my honer to look this project, now , I successfully call the opencv-camera to show in the web. But I want to design a client to load the video from the service, the reason is that I want to do a real time object-detection ,so I want to make  the fram from the camera to transorm my detection api, how can I do it?  I don't know how to use the fram from the web to load in the detection api. Please help me, give you my best wishes!
