### ISSUE TITLE
saving a photo

### ISSUE THREAD

**Issue by ffcruz85** [miguelgrinberg/flask-video-streaming#20]
I am trying to add a button for saving a snapshot. Forgive me my ignorance here, despite programming experience, this is actually my first Python project.

I would like to save a snapshot, preferably without refreshing the page. Any guidance here would be great. I appreciate this great project and your work on it. Here's all the info and code

 I am getting the following error:

![image](https://user-images.githubusercontent.com/2352828/41860740-00852812-7865-11e8-946d-f71c9fa3828e.png)

As a note, I am running the app multi-threaded, but I guess the mmal being used by the stream is another issue.

so far, here's my simple approach to test this. I have added a link with a route to run the code

```<html>
  <head>
    <title>Video Streaming Demonstration</title>
  </head>
  <body>
    <h1>Video Streaming Demonstration</h1>
    <a href="{{ url_for('take_pic') }}">Turn on</a><br/>
    <img src="{{ url_for('video_feed') }}">
  </body>
</html>
```

and here's my app.py
``` 
from flask import Flask, render_template, Response
from camera_pi import Camera
from picamera import PiCamera
app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html')


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@app.route('/video_feed')
def video_feed():
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@app.route('/take_pic')
def take_pic():
    with PiCamera() as camera:
        camera.capture('image.jpg')
    return '', 204  # no content

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', threaded=True)
```

**Comment by miguelgrinberg** [comment]
The problem is that you cannot create a second instance of the camera, since the video stream is already connected and streaming.

What you can do instead of creating a camera instance through picamera is to take the current frame stored by the video stream generator.  The `Camera()` object that is passed to the generator that produces the stream can also be used for this. Just save that camera instance to a variable, and then use `camera.frame` to get the current frame as a jpeg byte sequence. If you write that to a file, the result will be a compatible jpeg file.

**Comment by ffcruz85** [comment]
yea, I figured the instance was the issue. I will research on how to write the file and share the results. Let me know if you have any idea on where I should start. Thanks for the prompt response! great project!

**Comment by ffcruz85** [comment]
Got it! thanks for the tip!

''' 
@app.route('/snapshot')
def snapshot():
    cam = Camera()
    photo = cam.get_frame()
    file = open('test.jpg', 'wb+')
    file.write(photo)
    file.close()
    return render_template('index.html')
'''
