### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by bsdis** [miguelgrinberg/flask-video-streaming#22]
Hi Miguel
Great example - thanks. 
I implemented a wrapper around my own camera like you described and everything worked more or less out of the box so that was very cool.
Besides visualizing the jpeg stream on the site I would like to calculate a value from each frame (like the sum of all values) and show that in a live updating graph next to the video.
I got the live graph working using functionality from bokeh (from anaconda) with hardcoded dummy values, my only problem right now is how do I get access to the framestream from a different handler than the def video_feed()?
Do you have any ideas regarding this?
Below is the central code.

The live graph works by long polling on the handler /data.
So somehow i need to intercept frames in the /data handler and calculate the 
needed value.

`
x = list(np.arange(0, 6, 0.1))
y1 = [sin(xx) + random() for xx in x]
y2 = [sin(xx) + random() for xx in x]

@app.route('/data', methods=['GET', 'OPTIONS', 'POST'])
def hello_world():
    x.append(x[-1]+0.1)
    y1.append(sin(x[-1])+random())
    return jsonify(x=x[-500:],
                   y1=y1[-500:],
    )

@app.route('/')
def index():
    """Video streaming home page."""

    source = AjaxDataSource(data=dict(x=[], y1=[]),
                            data_url='/data',
                            polling_interval=100)

    p = figure(toolbar_location="above", sizing_mode="scale_width")
    p.toolbar.logo = None
    p.line(x='x', y='y1', source=source)
    p.x_range.follow = "end"
    p.x_range.follow_interval = 10
    script1, div1 = components(p)
    return render_template("dashboard.html",
                           div1=div1, script1=script1
    )

def gen(camera):
    """Video streaming generator function."""
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', threaded=True)
`

**Comment by miguelgrinberg** [comment]
Motion jpeg is a fairly limited format. I don't believe you can intercept frames in the browser, so your only choice is to do your calculations in the server, before you deliver each frame. But then you need to pass the results to the client. You can have a second generator that returns these values, but there is nothing to guarantee that the two streams are going to be in sync, and actually more than likely they will not be. If you want a solution that is perfectly in sync, the only way I can think of to do this with motion jpeg is to add the result of your calculation to the frame itself, and then deliver the combined frame that has the image and the calculation results.

**Comment by bsdis** [comment]
Hi Miguel, thank you for the answer.
I agree that keeping things in sync will be impossible even just because the camera generator is pushing frames while the other source is polling.
However its not that important that things are 100% in sync for this example. You said that i could have a second generator which returns those values. Do you by this mean i should make one instance of the camera object for each stream and thereby a generator for each stream, or should I somehow share a single camera object between multiple streams?

**Comment by miguelgrinberg** [comment]
@bsdis I meant that you can create a completely separate endpoint that also uses streaming, but instead of streaming frames it streams these results of your calculations. You will then need to write JavaScript to handle the results stream in the browser.

**Comment by bsdis** [comment]
Hi, thank you for this. 
I found that this is easier to do in tornado, however this gives me another issue.
In your code you do 
return Response(gen(Camera()),mimetype='multipart/x-mixed-replace; boundary=frame')
in the video_feed handler. Do you know how to do this in Tornado?

**Comment by miguelgrinberg** [comment]
Unfortunately I do not know how to create a stream with Tornado, sorry.
