### ISSUE TITLE
Ctrl-C does not actually exit

### ISSUE THREAD

**Issue by xoxota99** [miguelgrinberg/flask-video-streaming#27]
running "python app.py" on Raspberry PI, when I hit Ctrl-C to exit the app, nothing actually happens. The web page continues as normal with a video feed.

**Comment by miguelgrinberg** [comment]
The handling of Ctrl-C is controlled by the web server that you are using. One thing that maybe will help is to make the background camera thread a daemon thread (add `daemon=True` to the `Thread()` constructor).
