### ISSUE TITLE
AttributeError when running the program

### ISSUE THREAD

**Issue by flash76** [miguelgrinberg/flask-video-streaming#32]
I tried running the Python script with both `python` and `python3`, but I keep getting the same error: 
```python
with picamera.PiCamera() as camera:
AttributeError: 'module' object has no attribute 'PiCamera'
```
I installed all the dependencies in both Python and Python3.
I'm using a Raspberry Pi Camera v2 with Raspberry Pi Zero W.

**Comment by miguelgrinberg** [comment]
what is the output of `pip freeze`?

**Comment by flash76** [comment]
When I run `pip3 freeze`, I get 
`apturl==0.5.2 
asn1crypto==0.24.0
astroid==2.1.0
autopep8==1.4.3
blinker==1.4
Brlapi==0.6.7
certifi==2018.8.24
chardet==3.0.4
Click==7.0
command-not-found==0.3
cryptography==2.3
cupshelpers==1.0
defer==1.0.6
distro==1.3.0
distro-info==0.18
entrypoints==0.2.3.post3
Flask==1.0.2
httplib2==0.11.3
idna==2.6
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
keyring==15.1.0
keyrings.alt==3.1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.14.0
lazr.uri==1.0.3
lazy-object-proxy==1.3.1
louis==3.6.0
macaroonbakery==1.1.4
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
netifaces==0.10.4
oauth==1.0.1
oauthlib==2.0.6
olefile==0.46
pexpect==4.6.0
Pillow==5.2.0
protobuf==3.0.0
pycairo==1.16.2
pycodestyle==2.4.0
pycrypto==2.6.1
pycups==1.9.73
PyGObject==3.30.1
PyJWT==1.6.4
pylint==2.2.2
pymacaroons==0.13.0
PyNaCl==1.2.1
pyRFC3339==1.1
python-apt==1.7.0
python-debian==0.1.33
pytz==2018.5
pyxdg==0.25
PyYAML==3.12
reportlab==3.5.6
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
simplejson==3.15.0
six==1.12.0
system-service==0.3
systemd-python==234
typed-ast==1.2.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
vboxapi==1.0
wadllib==1.3.3
Werkzeug==0.14.1
wrapt==1.11.1
xkit==0.0.0
zope.interface==4.3.2
`

I get a bunch of errors when running `pip freeze`, so I used `pip3`

**Comment by miguelgrinberg** [comment]
Where is `picamera`? Please see the requirements.txt file for this application and install everything.

**Comment by flash76** [comment]
Ooops....I copied the packages from another computer...I updated my comment, and I did install the dependencies from `requirements-pi.txt`. I'm still getting "`module 'picamera' has no attribute 'PiCamera'`"

**Comment by miguelgrinberg** [comment]
Not sure what is the problem. Try reinstalling `picamera`, you are using the same version I use, and I do see a `PiCamera` class in there.
