### ISSUE TITLE
Static method in camera_opencv.py?

### ISSUE THREAD

**Issue by mohammad-saber** [miguelgrinberg/flask-video-streaming#34]
Thank you very much for sharing video streaming code. 

I am going to change the Camera class. I need to pass in some arguments to class methods. However, frames() method is defined as static method. Even, when I change it into instance method, I need to change the Base Camera Class to accept "self" as input argument. But, I prefer not to change the Base Camera Class. 

Would you please let me know the reason why you used static method in Camera class?

**Comment by miguelgrinberg** [comment]
If you have two or more people connected to the stream you still want one camera background thread. The `frames()` method is basically the engine that produces frames for this background thread, so it is not associated with a particular camera instance, it works for all of them, and that is why it is a static method.
