### ISSUE TITLE
How to inport different stream to play?

### ISSUE THREAD

**Issue by jeffreyhong0217** [miguelgrinberg/flask-video-streaming#37]
My project is about algorithm,now I want inport different stream at the same time,and play in the same web page,but I don't know how to solve it?
When click one url,inport it to algorithm program,then play in the web page!

**Comment by miguelgrinberg** [comment]
I'm not sure I understand your question, but if you implement the different streams as different URLs, then to switch between streams you can change the `src` attribute of your `<img>` tag using JavaScript.

**Comment by jeffreyhong0217** [comment]
@miguelgrinberg Can I interactively stop the thread, pass in another stream address, and then open the thread?If can,how to do it?tks

**Comment by miguelgrinberg** [comment]
The thread stops on its own when it has no clients connected.

**Comment by jeffreyhong0217** [comment]
But I want to stop the thread when it has clients connected!My requirement is that when  the page plays a video then click on another video url to switch play!

**Comment by miguelgrinberg** [comment]
You are thinking in a single client. I'm thinking in multiple clients, each potentially watching different videos. As I said, you can switch the URL of the stream from JS. A stream that lost all its clients will stop on its own.

**Comment by jeffreyhong0217** [comment]
OK,I got it!I am doing an algorithmic detection project,the page has multiple video stream address,an algorithmic detection program running in the background,and then click on different video stream address to enter the background for algorithmic detection and display on the page!Now I don't known how to achieve?

**Comment by miguelgrinberg** [comment]
This is a JavaScript question. There are many answers online, see https://stackoverflow.com/questions/7462119/dynamically-replace-img-src-attribute-with-jquery for one of them.
