### ISSUE TITLE
Web page does not fully load after combining your "socketio audio" and "flask-video-streaming"

### ISSUE THREAD

**Issue by cvaldez83** [miguelgrinberg/flask-video-streaming#39]
Hi Miguel, firstly I wanted to thank you for all the great work you've done. I'm a complete noob to programming so I apologize in advance for my question.  I'm trying to combine the capabilities of your "[flask-video-streaming](https://github.com/miguelgrinberg/flask-video-streaming)" and your "[socketio-examples/audio](https://github.com/miguelgrinberg/socketio-examples/tree/master/audio)" into one application.  My end-goal is to be able stream video from server (a raspberry pi) to the browser as well as be able to stream voice audio from the browser to the server.  I have combined them (see my forked repo [here](https://github.com/cvaldez83/flask-video-streaming/tree/socket_audio)) into one app but I think there's some process blocking going on because the webpage does not fully load.  After some troubleshooting, I think my [app.py](https://github.com/cvaldez83/flask-video-streaming/blob/socket_audio/app.py) gets hung up on the video streaming generator function (code line # 77).  Not sure what to do.  Am I just combining these two code repos incorrectly?

**Comment by miguelgrinberg** [comment]
Can't really say for sure, but my guess is that opencv is not going to play nice with eventlet. Try removing eventlet to confirm this theory.

**Comment by cvaldez83** [comment]
I don't think I'm using opencv because the camera attached to the raspberry pi is the official camera module (the one with a ribbon cable).  Also, I'm not sure from what file you'd like me to remove eventlet, I searched for the text "eventlet" in all the code files but nothing came up.

**Comment by miguelgrinberg** [comment]
It's actually the same, the Pi camera is also unlikely to be compatible with Eventlet. By removing eventlet I mean uninstalling it. Flask-SocketIO uses eventlet if it finds it installed. If the application works when eventlet is not installed, then this confirms that there is an incompatibility between camera access functions and eventlet.

**Comment by cvaldez83** [comment]
Yes! Uninstalling eventlet seemed to fix the blocking that was occuring with the video streaming generator function.  But now, I'm getting a 400 error on the client side related to the websocket connection.  To troubleshoot on server side, I enabled logging by adding "engineio_logger=True" to the SocketIO() constructor.  It says "Received request to upgrade to websocket".  I think you talk about this in the [flask-socketio documentation](https://flask-socketio.readthedocs.io/en/latest/) (something about having to install gevent-websocket package).  I'll give that a shot tomorrow and report back.

**Comment by miguelgrinberg** [comment]
@cvaldez83 I don't expect gevent to work either, sadly. When you use eventlet or gevent, all the functions that you call must be non-blocking. It's unlikely that the picamera package will work well with these frameworks.

The reason why WebSocket fails when you removed eventlet is that the Flask development web server does not have WebSocket support. For WebSocket to be active you need either eventlet or gevent-websocket.

**Comment by cvaldez83** [comment]
Oh I see.  It's a bummer to hear that the picamera package is unlikely to work well with eventlet or gevent.  Thanks for the help Miguel, truly appreciate it.
