### ISSUE TITLE
Only Getting a single frame to display when using picamera

### ISSUE THREAD

**Issue by devopsec** [miguelgrinberg/flask-video-streaming#40]
Hey Miguel,

I am working on a project that takes multiple camera streams and displays them in flask when a user connects.
My issue is that when I try to generate the frames in flask I only get the first frame and then the browser stops rendering the jpeg stream.

I am able to confirm correct data is getting to the flask server from the camera clients by using mplayer.
The full opensource project is here on github: https://github.com/devopsec/shomesec
I think the issue is that the data coming from the camera clients may need some extra parsing to properly format the frame before sending to flask?
My assumption was that this should work without parsing if I made the buffer size = frame size, but please let me know if that is a bad assumption
https://github.com/devopsec/shomesec/blob/master/httpserver/webserver.py#L38

**Comment by miguelgrinberg** [comment]
If mplayer plays the stream, then this is a problem on the browser side, not the server. Browsers don't have great support for motion-jpeg, it is an old and somewhat forgotten format. For example, I recall Chrome did not play a stream if you entered the URL directly in the navigation bar, but it did if the URL was embedded in a page.

**Comment by devopsec** [comment]
I finally figured out what my issue was on this one.
My issue ended up being due to having a multi-hop architecture for my app, therefore I had to parse out the jpeg images at the middle hop server to be able to stream them to the client.
Thanks for all your tutorials man, could not have made this far without your well written articles!
