### ISSUE TITLE
pass  extra variable to get_frames

### ISSUE THREAD

**Issue by cybermritunjay** [miguelgrinberg/flask-video-streaming#45]
I want to pass an additional argument to get frames
like:
> while True:
>         frame = camera.get_frame(arg1)
>         yield (b'--frame\r\n'
>                    b'Content-Type: image/jpeg\r\n\r\n' + dummy + b'\r\n')

But When I do This things break.
How can I achieve This

**Comment by miguelgrinberg** [comment]
Did you change the get_frame() function accordingly?
