### ISSUE TITLE
Stream delay keeps getting larger

### ISSUE THREAD

**Issue by ninn55** [miguelgrinberg/flask-video-streaming#48]
Hi,

Thanks for this tutorial. I am building a web app with some realtime streaming support. I am using the method described in this repo. But the delay is uncertain. sometimes delay is huge. Sometimes its fine. Most of the time the delay is getting larger over time. 

Where seems to be the problem?

**Comment by miguelgrinberg** [comment]
Have you checked how much data you are trying to push through the connection? You are probably sending more data than what your network connection can process. Try reducing the frame rate, the picture size, compress more aggressively, etc.
