### ISSUE TITLE
Calculating stream FPS

### ISSUE THREAD

**Issue by LeonLok** [miguelgrinberg/flask-video-streaming#49]
Hi Miguel,

I've been wanting to add an FPS counter to the camera stream. Do you perhaps know where I should start modifying the code that makes the most sense?

I was thinking of starting with the frames_iterator loop for _thread in base_camera.py that would calculate the rate of frames being sent to a client, but I'm unsure if that's the best way to go about it. 

I'm currently streaming using OpenCV, so I've also been thinking of perhaps modifying the code in camera_opencv.py instead. Do you have any advice on how I should approach this?

Many thanks!

**Comment by miguelgrinberg** [comment]
You can get the current time in the generator, each time it returns a frame. Then use those time samples to calculate the frame rate. That would work for all camera drivers.

**Comment by LeonLok** [comment]
Ah of course, that makes sense! Thanks!
