### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by mrcarbook** [miguelgrinberg/flask-video-streaming#5]
Hi,
i have tried to run your project on raspberry with PI Camera but when try to open it in chromium browser  i don't see anything otherwise it run with emulated mode. One question I should uncomment the line  "from amera_pi import Camera" in app.py when use  Pi Camera ?

**Comment by miguelgrinberg** [comment]
Yes, you should. This is explained in the blog post that introduced this project. Also note that if you are using the newer version of this server, you can set an environment variable to select the camera:

    $ export CAMERA=pi

But make sure you have the latest code in this repo for that.

**Comment by mrcarbook** [comment]
Hi Miguel,

there is an error in camera_pi.py file, you miss import time.

Regards


Da: Miguel Grinberg<mailto:notifications@github.com>
Inviato: mercoledì 9 agosto 2017 18:56
A: miguelgrinberg/flask-video-streaming<mailto:flask-video-streaming@noreply.github.com>
Cc: mrazure<mailto:antimo.musone@hotmail.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [miguelgrinberg/flask-video-streaming] Not Work (#5)


Yes, you should. This is explained in the blog post that introduced this project. Also note that if you are using the newer version of this server, you can set an environment variable to select the camera:

$ export CAMERA=pi

But make sure you have the latest code in this repo for that.

**Comment by miguelgrinberg** [comment]
Thanks! Missed that when I copied the changes from the Pi back to my laptop.
