### ISSUE TITLE
How to use base64 code for display?

### ISSUE THREAD

**Issue by hanxuanhuo** [miguelgrinberg/flask-video-streaming#50]
Hello I'm new for flask and html, I try to encode the frame into base64 and display on the webpage, but it not work when I use this change in index.html:
`<img src="data:;base64, {{ url_for('video_feed') }}">`

nor this:
`def gen(camera):
    """Video streaming generator function."""
    while True:
        frame = camera.get_frame()
        frame = bytes(frame, encoding='utf8')
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')`

Where should I modify the code?

**Comment by miguelgrinberg** [comment]
What are you trying to do?

**Comment by hanxuanhuo** [comment]
I was asked to encode the image to base64 and show it on webpage. It seems that I can display an image on web by 'data:;base64' in html file, but it not work on video file.

**Comment by miguelgrinberg** [comment]
The data URLs are for including static content directly in the HTML file, you can't associate them with a remote URL as you are doing.

You can use the data technique with any image format that supports animations, such as gif and png, but of course that has nothing to do with this project.
