### ISSUE TITLE
Something about app.run() when i use higher version flask

### ISSUE THREAD

**Issue by sjw111** [miguelgrinberg/flask-video-streaming#51]
When i run opencv-camera app with higner verison flask like 1.0.2,  the param "threaded" could be ignore to support multi-thread. 
(line 986 `options.setdefault("threaded", True)`  in newest flask app.py)

In addition, something is deprecated in MarkupSafe, do we need to upgrade?
(sry my English is not good~)

**Comment by miguelgrinberg** [comment]
The application works correctly in the latest Flask release. Did you see any problems?

**Comment by sjw111** [comment]
@miguelgrinberg There just have a problem about  `MarkupSafe` is that when i want to make a venv by requirements-opencv.txt, maybe it's a version problem of MarkupSafe.

```
Collecting MarkupSafe==1.0
  Downloading http://mirrors.aliyun.com/pypi/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz (14 kB)

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1x/jj3zwl3d6hl45j20pcsl20t40000gn/T/pip-install-lu2ptjvi/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
```

thanks for your reply

**Comment by miguelgrinberg** [comment]
Okay, now I understand. I have updated the requirement files, so this problem should not occur anymore. Thanks!
