### ISSUE TITLE
Working in IIS

### ISSUE THREAD

**Issue by catamaican** [miguelgrinberg/flask-video-streaming#52]
Hi,
i'm trying to do something similar to your project but using IIS - it works using just Flask but it does not work in combination with IIS

I've posted a question here: https://stackoverflow.com/questions/62000712/flask-iis-motion-jpeg

Thank you!

**Comment by miguelgrinberg** [comment]
Unfortunately I know nothing about IIS. I suggest you look at the server and client logs to see where is this stream breaking.
