### ISSUE TITLE
How to send meta data Along with the image stream ? 

### ISSUE THREAD

**Issue by H-cmd-sketch** [miguelgrinberg/flask-video-streaming#54]
How to send meta data in the yield function in flask streaming? 

I tried this code 
As an example I used this to the length of the image as an additional info.  I will add other info also. But I can't retrieve any info once I put the server's link in the Img tag in Javascript. Can I send any string information along with frames in flask streaming and retrieve it in Javascript 
yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n'
              b'Content-Length: ' + str(len(img)).encode()+ b'\r\n'
              b'\r\n'+ img + b'\r\n')

**Comment by miguelgrinberg** [comment]
This project uses the Motion-JPEG format to stream the video. This format does not allow for metadata to be sent along with the frames.

You can implement your own custom streaming and build a video player for it in the client, and then you can implement the stream in any format of your choosing including the metadata that you need.

**Comment by H-cmd-sketch** [comment]
Thank you very much for you fast response. I will try this approach. 
I also tried web socket connection to send the image along with the data. However I think the browser gets blocked with much frame requests. I would like to ask what is the best solution for my situation. is it the custom streaming ?

**Comment by miguelgrinberg** [comment]
Transmitting jpeg frames is not efficient. There are other much more complex video streaming protocols that will give you higher frame rates, but they are much harder to implement.  Here is a good intro: https://www.wowza.com/blog/streaming-protocols.
