### ISSUE TITLE
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a generator.

### ISSUE THREAD

**Issue by AhmedBhati** [miguelgrinberg/flask-video-streaming#55]
I am getting 
TypeError: 'generator' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a generator. 
on werkzeug when running the code can you tell me possible changes i have to make.
I am running the code in Jupyter Notebook
The version of flask I am working with is 1.1.2
The version of werkzeug i am working with is 1.0.1

**Comment by miguelgrinberg** [comment]
This is not a notebook app, it is a standalone web server.

**Comment by AhmedBhati** [comment]
So can you tell me how to run this standalone web server as in what platform to use to run this... I have tried with python idle but getting the same error

**Comment by AhmedBhati** [comment]
I got it..., Thanks
