### ISSUE TITLE
Can we sync Flask streaming response with OpenCV FPS

### ISSUE THREAD

**Issue by IsmaeilMW** [miguelgrinberg/flask-video-streaming#62]
I am working on a module to stream the OpenCV frame to web server using Flask. When I tested the script locally, the Frame rate of OpenCV and flask response are in sync.

The problem started to occur when, I deployed the script in cloud server. The OpenCV FPS and flask response rate are not in sync. Due to that, I lost some frame in between.

After debugging the code for some time, I found that if I decrease the image size to 1280*720 then flask responded after 1 sec. If, I decrease the size to 640 * 360 response rate increased. But still it's not in sync. I tried to restrict the FPS to 12 but not able to make it in sync.

Is there any way so that we can synchronize the flask response with OpenCV frame rate using image size 1280 * 720 with FPS 12 -15?
```
import cv2
import time
import threading
from flask import Flask, Response

app = Flask(__name__)

@app.route("/")
def index():
    """Video streaming home page."""
    return "Hello World"


def run_video():
    # grab global references to the video stream, output frame, and
    # lock variables
    global cap, outputFrame, lock
    total = 0
    fpsLimit = 0.8  # Restricting the FPS.
    startTime = time.time()
    # loop over frames from the video stream
    while True:
        cap = cv2.VideoCapture('input_video/camera_1.mp4')
        while (cap.isOpened()):
            nowTime = time.time()
            if (nowTime - startTime) > fpsLimit:
                ret, img = cap.read()
                print("FPS rate : ", int(1 / (nowTime - startTime)))
                startTime = time.time()
                if ret == True:
                    total += 1
                    with lock:
                        outputFrame = img.copy()


def generate():
    global outputFrame, lock, prev_response_time
    while True:
        with lock:
            if outputFrame is None:
                continue
            (flag, encodedImage) = cv2.imencode(".jpg", outputFrame)
            # ensure the frame was successfully encoded
            if not flag:
                continue
        
        current_time = time.time()
        response_time = current_time - prev_response_time
        print("display_response_time", int(1 / (response_time)))
        prev_response_time = current_time
        
        # yield the output frame in the byte format
        yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' +
               bytearray(encodedImage) + b'\r\n')


@app.route("/video_feed")
def video_feed():
    return Response(generate(),
                    mimetype="multipart/x-mixed-replace; boundary=frame")


# check to see if this is the main thread of execution
lock = threading.Lock()
prev_response_time = 0
if __name__ == '__main__':
    thread = threading.Thread(target=run_video)
    thread.daemon = True
    thread.start()
    # start the flask app
    app.run(host='0.0.0.0', threaded=True, port=5000)
# release the video stream pointer
# cap.stop()
```
https://stackoverflow.com/questions/66381734/can-we-sync-flask-streaming-response-with-opencv-fps

**Comment by miguelgrinberg** [comment]
Are you considering the speed of the network at all in this? A fast network will give you more FPS, a slow network will give you less.

**Comment by IsmaeilMW** [comment]
No, I didn't consider the speed.
As in my case, I am reading the frame in individual thread. Due to that, response is not in sync. 
I tried with queue by putting all the images so that I wont lose the frames. But, problem is at what speed should I send the data on OutputFrame variable?
If you have any other straight forward method, kindly respond.

**Comment by miguelgrinberg** [comment]
I'm not really sure what you are after. You should reduce the frame rate in your OpenCV source until you reach a point that Flask can keep up without dropping frames. Or else, you should assume that Flask will drop frames when it falls behind, which is in my opinion a good way to handle this.

**Comment by miguelgrinberg** [comment]
> but, if connection is slow

That was exactly my point. You are not doing any sort of adaptive streaming here, so you can't expect things to magically keep up. With this type of streaming dropping frames is the best option.
