### ISSUE TITLE
I want to send a string alongwith each frame.

### ISSUE THREAD

**Issue by akshdeep-singh** [miguelgrinberg/flask-video-streaming#66]
```python
def gen(camera):
    while True:
        frame = camera.get_frame()
        
        # here i want a new string to send along with each frame

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
```
```html
<html>
  <head>
    <title>Video Streaming Demonstration</title>
  </head>
  <body>
    <h1>Video Streaming Demonstration</h1>
    <img src="{{ url_for('video_feed') }}">
    <p><!-- string to be shown here --></p>
  </body>
</html>
```

**Comment by miguelgrinberg** [comment]
Sorry, the Motion-JPEG format does not allow metadata to be sent along with video frames.

**Comment by akshdeep-singh** [comment]
any alternatives?

**Comment by miguelgrinberg** [comment]
Nothing as easy as motion-jpeg. You can implement your own streaming protocol, and then implement a video renderer in your front end. Or maybe you can use a more advanced streaming protocol that supports subtitles or closed captions and then you have a place to enter your strings. Either way, this code will not work and cannot be easily adapted.

**Comment by BrettLL** [comment]
@akshdeep-singh have you found other methods to slove this problem?
