### ISSUE TITLE
Loading the video stream freezes up all other responses from the Flask server

### ISSUE THREAD

**Issue by NRockhouse** [miguelgrinberg/flask-video-streaming#67]
If I had the MJPEG stream loaded on a page, it seems to freezes up all other requests, including my SocketIO server which is from the `flask-socketio` library. Even for navigating to another page, since the MJPEG stream is still being streamed on the page, I had to unload it with `document.getElementsByTagName('img')[0].src = ''` first before it can hyperlink to another page successfully. Is there any way around this?

![image](https://user-images.githubusercontent.com/8848211/120309829-42a20080-c308-11eb-8535-932b922e9e09.png)

If I am on a page where the live stream does not need to be loaded, the SocketIO server loads fine.

![image](https://user-images.githubusercontent.com/8848211/120310148-a4fb0100-c308-11eb-8bf0-4502fc770ceb.png)

**Comment by miguelgrinberg** [comment]
Yes, you have to use a server that can handle more than one request at a time. Either with multiple processes or multiple threads. What is your current web server?

**Comment by NRockhouse** [comment]
I'm only on Flask which is routed through SocketIO's Flask wrapper, I didn't proxy it through nginx or any external servers. I've only just learnt about using Flask's web server so I'm not sure about the intricate details, but while checking the source code of SocketIO, since SocketIO's is already calling Flask with `threaded=True`, wouldn't that be threaded?

This is my arguments for calling Flask/SocketIO.
```python
if __name__ == "__main__":
    socketio.run(app, host='127.0.0.1', debug=True, use_reloader=False)
```

**Comment by miguelgrinberg** [comment]
@NRockhouse Okay, you didn't mention that you were using Socket.IO before. Are you using eventlet or gevent? Try removing them, these are likely incompatible with your camera hardware and will block when you access frames.

**Comment by NRockhouse** [comment]
I'm using `eventlet`. I think I'll split it into two Flask servers in that case as a workaround. Thanks a lot for the quick assistance!
