### ISSUE TITLE
Publish the video through MotionEye

### ISSUE THREAD

**Issue by konrul-r10** [miguelgrinberg/flask-video-streaming#83]
Hello,

I am trying to publish my OpenCV output video through motioneye. However, I am getting error when I do that.

The error is like that:

[mpjpeg @ 000001faffe92920] Expected boundary '--' not found, instead found a line of 68 bytes

or an other error like that:

Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Users\evren\AppData\Roaming\Python\Python39\site-packages\werkzeug\wsgi.py", line 462, in __next__
    return self._next()
  File "C:\Users\evren\AppData\Roaming\Python\Python39\site-packages\werkzeug\wrappers\response.py", line 49, in _iter_encoded
    for item in iterable:
  File "C:\Users\evren\Documents\ProjectROI\sandbox.py", line 55, in gen_frames
    roiColor = frame[x:y, x2:y2]
TypeError: 'NoneType' object is not subscriptable
192.168.1.12 - - [22/Aug/2022 01:02:48] "GET /motion HTTP/1.0" 200 -

I need some clue. In my opinion, if I try to connect 2 different way (from motion eye and web browser) the stream published by flask, there is a problem with it.

Hardware: Raspberry Pi 4 4GB
motionEye Version:	0.42.1
Motion Version:	4.3.2
OS Version:	Raspbian 11 (Bullseye)

**Comment by miguelgrinberg** [comment]
@konrul-r10 I don't understand what is this project's relation to your problem. Can you please explain?

**Comment by konrul-r10** [comment]
Hello again, I am sorry about my English, maybe I have explained my problem in a hard way.

I want to see my opencv output through the "motion eye" application. To do this, I have to publish opencv output. Thus, I have used flask to publish opencv output to the internet.

I have added the IP address given by the flask to the Motion Eye application. By this, I would be able to see my opencv output through the Motion Eye application together with my other surveillance cameras.

However, flask can't publish opencv output through the motion eye application. I get this error:

[mpjpeg @ 000001faffe92920] Expected boundary '--' not found, instead found a line of 68 bytes

Sometimes the error seems different, like this:

Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
File "C:\Users\evren\AppData\Roaming\Python\Python39\site-packages\werkzeug\wsgi.py", line 462, in next
return self._next()
File "C:\Users\evren\AppData\Roaming\Python\Python39\site-packages\werkzeug\wrappers\response.py", line 49, in _iter_encoded
for item in iterable:
File "C:\Users\evren\Documents\ProjectROI\sandbox.py", line 55, in gen_frames
roiColor = frame[x:y, x2:y2]
TypeError: 'NoneType' object is not subscriptable
192.168.1.12 - - [22/Aug/2022 01:02:48] "GET /motion HTTP/1.0" 200 -

Is there any way to solve this problem? I can share my codes if you want to help me with the problem.


I hope I could explain my question better. Thank you for your time and interest.

Best wishes.

**Comment by miguelgrinberg** [comment]
@konrul-r10 can you view your opencv stream directly from the Flask application? If that works, that means that your browser understands the stream, so my guess is that the issue is not with the stream itself but with your MotionEye application or the stream URL you are giving it.

**Comment by konrul-r10** [comment]
Thanks for your quick response. Yes I am able to see stream directly from flask.

However, I don't think so, it is not related to the motion eye application. When I use 2 different browser windows from the flask, it gives the same error.

**Comment by miguelgrinberg** [comment]
Well, I still don't understand what can I do to help with this. The only error that you showed here is an error in your own application, not in this one. I do not recognize a file called sandbox.py or a variable called `roiColor`. That must be your own code, correct?

**Comment by konrul-r10** [comment]
Hello again, I found the problem. My RPi 4 Bullseye system has opencv installation from pip which is not supporting C++ headers. Therefore I am having such a problem. I am sorry for bothering you with this issue. However,  if someone has the same problem, they can now find out why. Thanks.
