### ISSUE TITLE
Stopping/Restarting video stream?

### ISSUE THREAD

**Issue by donskytech** [miguelgrinberg/flask-video-streaming#87]
Hi,

I am not sure how to do what I want, but is it possible to restart the video stream once again when you stop it?

I have this logic that needs to analyze the captured frame from my Camera and it would return true or false and it should stop the generator function or not.

On the other hand, an event from the client should restart the video stream.

Is what I am thinking correct or feasible or there is a better way of doing this?

```
is_ok = True

def analyze_frame(frame):
	# frame needs to be analyze then it would return if it is true or false
	pass
	
def restart_stream():
	global is_ok
	is_ok = True

def gen(camera):
    """Video streaming generator function."""
    yield b'--frame\r\n'
	
	# Can this be done?
    while is_ok:
        frame = camera.get_frame()
	is_ok = analyze_frame(frame)
		
        yield b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n--frame\r\n'


@app.route('/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')
```

**Comment by miguelgrinberg** [comment]
This is a Motion JPEG stream, which is a very limited form of video streaming. How a stop/restart is handled really depends on how the different browsers implement their Motion JPEG players. I would suggest that instead of stopping the stream you keep the stream running and send a repeat frame, so that it looks like the stream stopped. A real stop and resume will need to be tested on all browsers to make sure it is handled well.

**Comment by donskytech** [comment]
Oh, so the idea is not to stop the generator stream but show a repeat frame!
Yeah, sounds reasonable.
Thanks!

**OFF-TOPIC:**
I would like to ask something not related, I just don't know where to reach you.

I am doing a lot of IoT projects and I find WebSocket(Flask-SocketIO, Flask-Sock) to be a little over the top and looking for a simpler solution like Server-Sent-Events.

Do you happen to have an idea how to best do this in a Flask application running on a Rasberry Pi?

I actually have been evangelizing your MicroDot framework (in MicroPython) by doing loT projects with it and doing my best to write good blog content.   

The reality is, I could not find enough solutions for both Flask and MicroDot.  

Sorry to hijack this thread, please feel free to let me know where is the proper forum.

**Comment by miguelgrinberg** [comment]
Thanks for blogging about microdot! I have seen some of your posts already, good stuff!

If you are looking for SSE in Microdot that is not available yet, but it is in my todo list to implement at some point. The WebSocket implementation in microdot is fairly simple and easy to use, and it also works when using microdot in standard Python, without any code changes. It does not work with Flask, however.

**Comment by donskytech** [comment]
Thanks for the kind words!
