### ISSUE TITLE
Return still image when requested

### ISSUE THREAD

**Issue by askpatrickw** [miguelgrinberg/flask-video-streaming#88]
When integrating [MJPEG cameras with Home Assistant (HA)](https://www.home-assistant.io/integrations/mjpeg/), there is an option to configure a URL to a still image (thumbnail) as well as to the stream.

This allows the Home Assistant Dashboards to show a thumbnail that is updated periodically and to also allow click-through to see the live feed. As opposed to live feeds on the dashboard.

**Implementation Thoughts**

Originally I was thinking the still could be generated periodically, or on motion, but I think the simplest approach would be an endpoint for HA to call to get a still.

Let me know if this interesting to the core project or not.

**Comment by miguelgrinberg** [comment]
I don't see this as part of this project. The idea of this repository is to demonstrate how to implement the video streaming aspect, and the intention is for this code to be a companion to my blog articles on this topic. Adding other features would make more sense on a dedicated project, which you may want to based off of this code, if you like.

**Comment by askpatrickw** [comment]
Sounds good, for future searchers, this mostly works... 

It does seem to have some sort of timing issue when adding the MJPEG config in Home Assistant. Sometimes the thumbnail doesn't validate. If I figure out a better solution, I'll post another comment on this closed issue.

```python
@app.route("/thumbnail")
def get_thumbnail():
    frame = flask_cam.get_frame()
    # return b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n--frame\r\n"
    return Response(frame, mimetype="image/jpeg")
```
